In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
filename = '/Users/reuven/Courses/Current/data/olympic_athlete_events.csv'

df = pd.read_csv(filename)

In [3]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [6]:
# I want to find all games from 2012

df.loc[
   df['Year'] == 2012]   # row selector

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
98,34,Jamale (Djamel-) Aarrass (Ahrass-),M,30.0,187.0,76.0,France,FRA,2012 Summer,2012,Summer,London,Athletics,"Athletics Men's 1,500 metres",NaN
134,48,Abdelhak Aatakni,M,24.0,NaN,64.0,Morocco,MAR,2012 Summer,2012,Summer,London,Boxing,Boxing Men's Light-Welterweight,NaN
164,67,Mariya Vasilyevna Abakumova (-Tarabina),F,26.0,179.0,80.0,Russia,RUS,2012 Summer,2012,Summer,London,Athletics,Athletics Women's Javelin Throw,NaN
174,73,Luc Abalo,M,27.0,182.0,86.0,France,FRA,2012 Summer,2012,Summer,London,Handball,Handball Men's Handball,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271020,135526,Dniel Zwickl,M,27.0,178.0,71.0,Hungary,HUN,2012 Summer,2012,Summer,London,Table Tennis,Table Tennis Men's Singles,NaN
271023,135528,Marc Zwiebler,M,28.0,181.0,75.0,Germany,GER,2012 Summer,2012,Summer,London,Badminton,Badminton Men's Singles,NaN
271052,135547,Viktoriya Viktorovna Zyabkina,F,19.0,174.0,62.0,Kazakhstan,KAZ,2012 Summer,2012,Summer,London,Athletics,Athletics Women's 200 metres,NaN
271090,135557,Dominik ycki,M,38.0,192.0,95.0,Poland,POL,2012 Summer,2012,Summer,London,Sailing,Sailing Men's Two Person Keelboat,NaN
271091,135558,ukasz Tomasz ygado,M,32.0,200.0,89.0,Poland,POL,2012 Summer,2012,Summer,London,Volleyball,Volleyball Men's Volleyball,NaN

In [7]:
df.set_index('Year')

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Season,City,Sport,Event,Medal
Year,,,,,,,,,,,,,,
1992,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
2012,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
1920,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,Summer,Antwerpen,Football,Football Men's Football,NaN
1900,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
1988,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1976,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
2014,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
2014,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
1998,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
2002,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [8]:
df = df.set_index('Year')

In [9]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Season,City,Sport,Event,Medal
Year,,,,,,,,,,,,,,
1992,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
2012,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
1920,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,Summer,Antwerpen,Football,Football Men's Football,NaN
1900,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
1988,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [10]:
df.loc[1992]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Season,City,Sport,Event,Medal
Year,,,,,,,,,,,,,,
1992,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1992,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,Winter,Albertville,Speed Skating,Speed Skating Women's 500 metres,NaN
1992,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,Winter,Albertville,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
1992,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
1992,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1992,135514,Tamara Zwart,F,17.0,167.0,57.0,Netherlands,NED,1992 Summer,Summer,Barcelona,Synchronized Swimming,Synchronized Swimming Women's Duet,NaN
1992,135523,"Ronald Ferdinand ""Ron"" Zwerver",M,25.0,200.0,93.0,Netherlands,NED,1992 Summer,Summer,Barcelona,Volleyball,Volleyball Men's Volleyball,Silver
1992,135531,Sabine Beate Zwiener (-Jauchstetter),F,24.0,172.0,52.0,Germany,GER,1992 Summer,Summer,Barcelona,Athletics,Athletics Women's 800 metres,NaN
1992,135537,Sawomir Andrzej Zwierzyski,M,25.0,175.0,72.0,Poland,POL,1992 Summer,Summer,Barcelona,Fencing,"Fencing Men's epee, Team",NaN
1992,135545,Henk Jan Zwolle,M,27.0,197.0,93.0,Netherlands,NED,1992 Summer,Summer,Barcelona,Rowing,Rowing Men's Double Sculls,Bronze

In [11]:
# let's set the index to be both the year and the season

# (1) reset the index to its default, and make Year a regular column
df = df.reset_index()
df.head()

,Year,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Season,City,Sport,Event,Medal
0,1992,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2012,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,1920,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,Summer,Antwerpen,Football,Football Men's Football,NaN
3,1900,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,1988,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [12]:
# (2) set the index to be both the Year and the Season columns

df = df.set_index(['Year', 'Season'])
df.head()

,,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,City,Sport,Event,Medal
Year,Season,,,,,,,,,,,,,
1992,Summer,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
2012,Summer,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
1920,Summer,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,Antwerpen,Football,Football Men's Football,NaN
1900,Summer,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
1988,Winter,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [13]:
# I can search based on both elements of the multi-index

df.loc[(1992, 'Summer')]

/var/folders/rr/0mnyyv811fs5vyp22gf4fxk00000gn/T/ipykernel_55766/2075995050.py:3: PerformanceWarning: indexing past lexsort depth may impact performance.
  df.loc[(1992, 'Summer')]

                 ID                                  Name Sex   Age  Height  \
Year Season
1992 Summer       1                             A Dijiang   M  24.0   180.0
     Summer      33                   Mika Lauri Aarnikka   M  24.0   187.0
     Summer      43                 Morten Gjerdrum Aasen   M  34.0   185.0
     Summer      50                            Arvi Aavik   M  22.0   185.0
     Summer      64                        M'Bairo Abakar   M  31.0     NaN
...             ...                                   ...  ..   ...     ...
     Summer  135514                          Tamara Zwart   F  17.0   167.0
     Summer  135523        Ronald Ferdinand "Ron" Zwerver   M  25.0   200.0
     Summer  135531  Sabine Beate Zwiener (-Jauchstetter)   F  24.0   172.0
     Summer  135537            Sawomir Andrzej Zwierzyski   M  25.0   175.0
     Summer  135545                       Henk Jan Zwolle   M  27.0   197.0

             Weight         Team  NOC        Games       City  \
Year Season
1992 Summer    80.0        China  CHN  1992 Summer  Barcelona
     Summer    76.0      Finland  FIN  1992 Summer  Barcelona
     Summer    75.0       Norway  NOR  1992 Summer  Barcelona
     Summer   106.0      Estonia  EST  1992 Summer  Barcelona
     Summer     NaN         Chad  CHA  1992 Summer  Barcelona
...             ...          ...  ...          ...        ...
     Summer    57.0  Netherlands  NED  1992 Summer  Barcelona
     Summer    93.0  Netherlands  NED  1992 Summer  Barcelona
     Summer    52.0      Germany  GER  1992 Summer  Barcelona
     Summer    72.0       Poland  POL  1992 Summer  Barcelona
     Summer    93.0  Netherlands  NED  1992 Summer  Barcelona

                             Sport                                    Event  \
Year Season
1992 Summer             Basketball              Basketball Men's Basketball
     Summer                Sailing          Sailing Men's Two Person Dinghy
     Summer          Equestrianism  Equestrianism Mixed Jumping, Individual
     Summer              Wrestling   Wrestling Men's Heavyweight, Freestyle
     Summer                   Judo             Judo Men's Half-Middleweight
...                            ...                                      ...
     Summer  Synchronized Swimming       Synchronized Swimming Women's Duet
     Summer             Volleyball              Volleyball Men's Volleyball
     Summer              Athletics             Athletics Women's 800 metres
     Summer                Fencing                 Fencing Men's epee, Team
     Summer                 Rowing               Rowing Men's Double Sculls

              Medal
Year Season
1992 Summer     NaN
     Summer     NaN
     Summer     NaN
     Summer     NaN
     Summer     NaN
...             ...
     Summer     NaN
     Summer  Silver
     Summer     NaN
     Summer     NaN
     Summer  Bronze

[12977 rows x 13 columns]

In [14]:
# sort_index returns a new data frame, based on df, in which the index is sorted
df = df.sort_index()

df.head()

               ID                                Name Sex  Age  Height  \
Year Season
1896 Summer  1724              Aristidis Akratopoulos   M  NaN     NaN
     Summer  1724              Aristidis Akratopoulos   M  NaN     NaN
     Summer  1725  Konstantinos "Kostas" Akratopoulos   M  NaN     NaN
     Summer  1725  Konstantinos "Kostas" Akratopoulos   M  NaN     NaN
     Summer  4113                  Anastasios Andreou   M  NaN     NaN

             Weight      Team  NOC        Games    City      Sport  \
Year Season
1896 Summer     NaN    Greece  GRE  1896 Summer  Athina     Tennis
     Summer     NaN  Greece-3  GRE  1896 Summer  Athina     Tennis
     Summer     NaN    Greece  GRE  1896 Summer  Athina     Tennis
     Summer     NaN  Greece-3  GRE  1896 Summer  Athina     Tennis
     Summer     NaN    Greece  GRE  1896 Summer  Athina  Athletics

                                          Event Medal
Year Season
1896 Summer                Tennis Men's Singles   NaN
     Summer                Tennis Men's Doubles   NaN
     Summer                Tennis Men's Singles   NaN
     Summer                Tennis Men's Doubles   NaN
     Summer  Athletics Men's 110 metres Hurdles   NaN

In [15]:
df.loc[(1992, 'Summer')]

                 ID                                  Name Sex   Age  Height  \
Year Season
1992 Summer       1                             A Dijiang   M  24.0   180.0
     Summer      33                   Mika Lauri Aarnikka   M  24.0   187.0
     Summer      43                 Morten Gjerdrum Aasen   M  34.0   185.0
     Summer      50                            Arvi Aavik   M  22.0   185.0
     Summer      64                        M'Bairo Abakar   M  31.0     NaN
...             ...                                   ...  ..   ...     ...
     Summer  135514                          Tamara Zwart   F  17.0   167.0
     Summer  135523        Ronald Ferdinand "Ron" Zwerver   M  25.0   200.0
     Summer  135531  Sabine Beate Zwiener (-Jauchstetter)   F  24.0   172.0
     Summer  135537            Sawomir Andrzej Zwierzyski   M  25.0   175.0
     Summer  135545                       Henk Jan Zwolle   M  27.0   197.0

             Weight         Team  NOC        Games       City  \
Year Season
1992 Summer    80.0        China  CHN  1992 Summer  Barcelona
     Summer    76.0      Finland  FIN  1992 Summer  Barcelona
     Summer    75.0       Norway  NOR  1992 Summer  Barcelona
     Summer   106.0      Estonia  EST  1992 Summer  Barcelona
     Summer     NaN         Chad  CHA  1992 Summer  Barcelona
...             ...          ...  ...          ...        ...
     Summer    57.0  Netherlands  NED  1992 Summer  Barcelona
     Summer    93.0  Netherlands  NED  1992 Summer  Barcelona
     Summer    52.0      Germany  GER  1992 Summer  Barcelona
     Summer    72.0       Poland  POL  1992 Summer  Barcelona
     Summer    93.0  Netherlands  NED  1992 Summer  Barcelona

                             Sport                                    Event  \
Year Season
1992 Summer             Basketball              Basketball Men's Basketball
     Summer                Sailing          Sailing Men's Two Person Dinghy
     Summer          Equestrianism  Equestrianism Mixed Jumping, Individual
     Summer              Wrestling   Wrestling Men's Heavyweight, Freestyle
     Summer                   Judo             Judo Men's Half-Middleweight
...                            ...                                      ...
     Summer  Synchronized Swimming       Synchronized Swimming Women's Duet
     Summer             Volleyball              Volleyball Men's Volleyball
     Summer              Athletics             Athletics Women's 800 metres
     Summer                Fencing                 Fencing Men's epee, Team
     Summer                 Rowing               Rowing Men's Double Sculls

              Medal
Year Season
1992 Summer     NaN
     Summer     NaN
     Summer     NaN
     Summer     NaN
     Summer     NaN
...             ...
     Summer     NaN
     Summer  Silver
     Summer     NaN
     Summer     NaN
     Summer  Bronze

[12977 rows x 13 columns]

In [16]:
# let's make our index have year, season, and sport

df = df.reset_index()
df = df.set_index(['Year', 'Season', 'Sport'])
df = df.sort_index()
df.head()

                          ID                       Name Sex   Age  Height  \
Year Season Sport
1896 Summer Athletics   4113         Anastasios Andreou   M   NaN     NaN
            Athletics   9760           Spyridon Belokas   M   NaN     NaN
            Athletics  12068       Arthur Charles Blake   M  24.0     NaN
            Athletics  12068       Arthur Charles Blake   M  24.0     NaN
            Athletics  16616  Thomas Edmund "Tom" Burke   M  21.0   183.0

                       Weight           Team  NOC        Games    City  \
Year Season Sport
1896 Summer Athletics     NaN         Greece  GRE  1896 Summer  Athina
            Athletics     NaN         Greece  GRE  1896 Summer  Athina
            Athletics     NaN  United States  USA  1896 Summer  Athina
            Athletics     NaN  United States  USA  1896 Summer  Athina
            Athletics    66.0  United States  USA  1896 Summer  Athina

                                                    Event   Medal
Year Season Sport
1896 Summer Athletics  Athletics Men's 110 metres Hurdles     NaN
            Athletics            Athletics Men's Marathon     NaN
            Athletics        Athletics Men's 1,500 metres  Silver
            Athletics            Athletics Men's Marathon     NaN
            Athletics          Athletics Men's 100 metres    Gold

In [17]:
# I can retrieve by year
df.loc[1992]

                          ID                           Name Sex   Age  Height  \
Season Sport
Summer Archery          3656       Jos Andrs Anchondo Garca   M  29.0   185.0
       Archery          3656       Jos Andrs Anchondo Garca   M  29.0   185.0
       Archery          5447          Loedmila Arzjannikova   F  34.0   168.0
       Archery          5447          Loedmila Arzjannikova   F  34.0   168.0
       Archery          8174  Jack Leonard "Jay" Barrs, Jr.   M  30.0   182.0
...                      ...                            ...  ..   ...     ...
Winter Speed Skating  135071                     Olaf Zinke   M  25.0   182.0
       Speed Skating  135071                     Olaf Zinke   M  25.0   182.0
       Speed Skating  135071                     Olaf Zinke   M  25.0   182.0
       Speed Skating  135381      Angela Zuckerman (-Davre)   F  26.0   175.0
       Speed Skating  135381      Angela Zuckerman (-Davre)   F  26.0   175.0

                      Weight           Team  NOC        Games         City  \
Season Sport
Summer Archery          75.0         Mexico  MEX  1992 Summer    Barcelona
       Archery          75.0         Mexico  MEX  1992 Summer    Barcelona
       Archery          62.0   Unified Team  EUN  1992 Summer    Barcelona
       Archery          62.0   Unified Team  EUN  1992 Summer    Barcelona
       Archery          70.0  United States  USA  1992 Summer    Barcelona
...                      ...            ...  ...          ...          ...
Winter Speed Skating    80.0        Germany  GER  1992 Winter  Albertville
       Speed Skating    80.0        Germany  GER  1992 Winter  Albertville
       Speed Skating    80.0        Germany  GER  1992 Winter  Albertville
       Speed Skating    65.0  United States  USA  1992 Winter  Albertville
       Speed Skating    65.0  United States  USA  1992 Winter  Albertville

                                                   Event   Medal
Season Sport
Summer Archery                  Archery Men's Individual     NaN
       Archery                        Archery Men's Team     NaN
       Archery                Archery Women's Individual     NaN
       Archery                      Archery Women's Team  Bronze
       Archery                  Archery Men's Individual     NaN
...                                                  ...     ...
Winter Speed Skating      Speed Skating Men's 500 metres     NaN
       Speed Skating    Speed Skating Men's 1,000 metres    Gold
       Speed Skating    Speed Skating Men's 1,500 metres     NaN
       Speed Skating  Speed Skating Women's 1,500 metres     NaN
       Speed Skating  Speed Skating Women's 3,000 metres     NaN

[16413 rows x 12 columns]

In [18]:
# I can retrieve by year + season

df.loc[(1992, 'Summer')]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,City,Event,Medal
Sport,,,,,,,,,,,,
Archery,3656,Jos Andrs Anchondo Garca,M,29.0,185.0,75.0,Mexico,MEX,1992 Summer,Barcelona,Archery Men's Individual,NaN
Archery,3656,Jos Andrs Anchondo Garca,M,29.0,185.0,75.0,Mexico,MEX,1992 Summer,Barcelona,Archery Men's Team,NaN
Archery,5447,Loedmila Arzjannikova,F,34.0,168.0,62.0,Unified Team,EUN,1992 Summer,Barcelona,Archery Women's Individual,NaN
Archery,5447,Loedmila Arzjannikova,F,34.0,168.0,62.0,Unified Team,EUN,1992 Summer,Barcelona,Archery Women's Team,Bronze
Archery,8174,"Jack Leonard ""Jay"" Barrs, Jr.",M,30.0,182.0,70.0,United States,USA,1992 Summer,Barcelona,Archery Men's Individual,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
Wrestling,134124,Wodzimierz Jan Zawadzki,M,24.0,167.0,60.0,Poland,POL,1992 Summer,Barcelona,"Wrestling Men's Featherweight, Greco-Roman",NaN
Wrestling,134304,Jaroslav Zeman,M,30.0,174.0,76.0,Czechoslovakia,TCH,1992 Summer,Barcelona,"Wrestling Men's Welterweight, Greco-Roman",NaN
Wrestling,134408,Elmadi Zaynaydiyevich Zhabrailov,M,26.0,182.0,85.0,Unified Team,EUN,1992 Summer,Barcelona,"Wrestling Men's Middleweight, Freestyle",Silver
Wrestling,134716,Valentin Dimitrov Zhelev,M,23.0,174.0,74.0,Bulgaria,BUL,1992 Summer,Barcelona,"Wrestling Men's Welterweight, Freestyle",NaN
Wrestling,135403,Eduards ukovs,M,20.0,175.0,62.0,Latvia,LAT,1992 Summer,Barcelona,"Wrestling Men's Featherweight, Freestyle",NaN

In [19]:
# retrieve by three parts of the multi-index
df.loc[(1992, 'Summer', 'Archery')]

                         ID                                 Name Sex   Age  \
Year Season Sport
1992 Summer Archery    3656             Jos Andrs Anchondo Garca   M  29.0
            Archery    3656             Jos Andrs Anchondo Garca   M  29.0
            Archery    5447                Loedmila Arzjannikova   F  34.0
            Archery    5447                Loedmila Arzjannikova   F  34.0
            Archery    8174        Jack Leonard "Jay" Barrs, Jr.   M  30.0
...                     ...                                  ...  ..   ...
            Archery  132302                     Hiroshi Yamamoto   M  29.0
            Archery  132910       Vladimir Nikolayevich Yesheyev   M  34.0
            Archery  132910       Vladimir Nikolayevich Yesheyev   M  34.0
            Archery  133609  Stanislav Vyacheslavovich Zabrodsky   M  30.0
            Archery  133609  Stanislav Vyacheslavovich Zabrodsky   M  30.0

                     Height  Weight           Team  NOC        Games  \
Year Season Sport
1992 Summer Archery   185.0    75.0         Mexico  MEX  1992 Summer
            Archery   185.0    75.0         Mexico  MEX  1992 Summer
            Archery   168.0    62.0   Unified Team  EUN  1992 Summer
            Archery   168.0    62.0   Unified Team  EUN  1992 Summer
            Archery   182.0    70.0  United States  USA  1992 Summer
...                     ...     ...            ...  ...          ...
            Archery   170.0    71.0          Japan  JPN  1992 Summer
            Archery   185.0    78.0   Unified Team  EUN  1992 Summer
            Archery   185.0    78.0   Unified Team  EUN  1992 Summer
            Archery   187.0    72.0   Unified Team  EUN  1992 Summer
            Archery   187.0    72.0   Unified Team  EUN  1992 Summer

                          City                       Event   Medal
Year Season Sport
1992 Summer Archery  Barcelona    Archery Men's Individual     NaN
            Archery  Barcelona          Archery Men's Team     NaN
            Archery  Barcelona  Archery Women's Individual     NaN
            Archery  Barcelona        Archery Women's Team  Bronze
            Archery  Barcelona    Archery Men's Individual     NaN
...                        ...                         ...     ...
            Archery  Barcelona          Archery Men's Team     NaN
            Archery  Barcelona    Archery Men's Individual     NaN
            Archery  Barcelona          Archery Men's Team     NaN
            Archery  Barcelona    Archery Men's Individual     NaN
            Archery  Barcelona          Archery Men's Team     NaN

[247 rows x 12 columns]

In [24]:
# what if I want to find all of the people who participated in Archery across all years and seasons?
# basically: any year, any season, but just Archery

df.xs('Archery', level='Sport')

                 ID                   Name Sex   Age  Height  Weight  \
Year Season
1900 Summer    9069   douard Beaudoin, Jr.   M   NaN     NaN     NaN
     Summer   27560                  Denet   M   NaN     NaN     NaN
     Summer   30112            Druart, Jr.   M   NaN     NaN     NaN
     Summer   35601       mile Lon Fisseux   M  32.0     NaN     NaN
     Summer   36505        Emmanuel Foulon   M  28.0     NaN     NaN
...             ...                    ...  ..   ...     ...     ...
2016 Summer  131983  Daniel Rezende Xavier   M  33.0   191.0    81.0
     Summer  132041                Xing Yu   M  25.0   188.0    90.0
     Summer  132041                Xing Yu   M  25.0   188.0    90.0
     Summer  133310            Yu Guan-Lin   M  22.0   172.0    59.0
     Summer  133310            Yu Guan-Lin   M  22.0   172.0    59.0

                       Team  NOC        Games            City  \
Year Season
1900 Summer          France  FRA  1900 Summer           Paris
     Summer          France  FRA  1900 Summer           Paris
     Summer         Belgium  BEL  1900 Summer           Paris
     Summer          France  FRA  1900 Summer           Paris
     Summer         Belgium  BEL  1900 Summer           Paris
...                     ...  ...          ...             ...
2016 Summer          Brazil  BRA  2016 Summer  Rio de Janeiro
     Summer           China  CHN  2016 Summer  Rio de Janeiro
     Summer           China  CHN  2016 Summer  Rio de Janeiro
     Summer  Chinese Taipei  TPE  2016 Summer  Rio de Janeiro
     Summer  Chinese Taipei  TPE  2016 Summer  Rio de Janeiro

                                               Event   Medal
Year Season
1900 Summer  Archery Men's Au Cordon Dore, 50 metres     NaN
     Summer  Archery Men's Au Cordon Dore, 50 metres     NaN
     Summer   Archery Men's Sur La Perche a La Herse  Silver
     Summer  Archery Men's Au Cordon Dore, 50 metres  Bronze
     Summer   Archery Men's Sur La Perche a La Herse    Gold
...                                              ...     ...
2016 Summer                       Archery Men's Team     NaN
     Summer                 Archery Men's Individual     NaN
     Summer                       Archery Men's Team     NaN
     Summer                 Archery Men's Individual     NaN
     Summer                       Archery Men's Team     NaN

[2334 rows x 12 columns]

In [26]:
# Let's find the average height of people in Archery over all years of the Olympics

df.xs('Archery', level='Sport')['Height'].mean()

173.2030848329049

In [28]:
df.xs('Archery', level='Sport')[['Height', 'Weight']].mean()

Height    173.203085
Weight     70.011135
dtype: float64

In [31]:
# what if I want to specify more than one thing with xs?
# for example: I want 1992, all seasons, archery

df.xs((1992, 'Archery'), level=['Year', 'Sport'])[['Height', 'Weight']].mean()

Height    174.095238
Weight     67.497354
dtype: float64